name: akit
description: App开发工具集 (Created by dokit 0.8.2-nullsafety.10)
version: 0.1.10
homepage: https://www.dokit.cn/#/index/home


environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  date_format: any
  vm_service: any
  package_info_plus: any
  shared_preferences: any
  image: 4.2.0
  google_fonts: any
  string_scanner: any
  path_provider: any
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true

  assets:
    - images/dokit_ic_close.png
    - images/dk_frame_hist.png
    - images/dk_method_channel.png
    - images/dk_sys_info.png
    - images/dk_view_check.png
    - images/dk_log_info.png
    - images/dk_ram.png
    - images/dk_view_route.png
    - images/dk_net_monitor.png
    - images/dokit_flutter_btn.png
    - images/dk_channel_check_h.png
    - images/dk_channel_check_n.png
    - images/dk_channel_expand_h.png
    - images/dk_channel_expand_n.png
    - images/dk_fps_chart.png
    - images/dk_route_arrow.png
    - images/dk_memory_search.png
    - images/dk_color_pick.png
    - images/dk_source_code.png
    - images/dk_time_counter.png
    - images/dokit_crash.png